Microverse Portfolio Project
kingnoel/microverse_portfolio pull request #1
Opened 2022-12-02 18:04 UTC by kingnoel

1. Use html an css linters.

2. Built two sections:
the toolbar (or header):
the headline section (right after the header):

2022-12-02 18:15 UTC, Ugboaja-Uchechi reviewed
Hi @kingnoel, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that all linters don't pass and the Readme doesn't follow the template provided by Microverse. Kindly adjust your Readme to follow this [template](https://github.com/microverseinc/readme-template) and make sure all linters pass before re-submitting 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-12-02 20:23 UTC, Debas-31 reviewed
Hi @kingnoel  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :negative_squared_cross_mark:  :negative_squared_cross_mark:  :negative_squared_cross_mark: 

- [ ] You have submitted a project with a linters error.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-03 11:37 UTC, iambenkis requested changes
Hi @MarcoDDM , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that needs to satisfy the following requirements:
- [ ] You have submitted a project with a linters error, Kindly fix them and then request another review
- [ ] You could fix them by running this command 
`npx stylelint "**/*.{css,scss}"  —fix`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-03 12:00 UTC, kingnoel commented
@iambenkis Thanks, I just did.
npx stylelint "**/*.{css,scss}" --fix is the correct command and not npx stylelint "**/*.{css,scss}" -fix

2022-12-03 14:30 UTC, Gambit142 reviewed
Hi @kingnoel 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not use the recommended README.md file. Kindly use this recommended [README.md](https://github.com/microverseinc/readme-template) file. Please stick to the design of the template but customize each section according to the requirements and nature of the project. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-03 17:05 UTC, Debas-31 requested changes
> ## Hi @kingnoel  :wave:
# Status: Required Change :recycle:
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights 
- Linters setup :heavy_check_mark:
- GitHub flow :heavy_check_mark: 
- Commit message :heavy_check_mark:
 
## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 17:05 UTC, Debas-31 commented on index.html
> +             <a href="microverse.org" class="item"><img src="img/svg/Vector-10.svg"/></a>
- [x] I think it's better to use the unordered list `ul and li` instead of the `section tag.` :+1: 

Example
```
<ul>
  <li>Item One</li>
  <li>Item Two</li>
  <li>Item Three</li>
  <li>Item Four</li>
  <li>Item Five</li>
</ul>
```

2022-12-03 17:05 UTC, Debas-31 commented on index.html
> +
- [x] Kindly change the p tag to the anchor tag to be linked with a specific address.

2022-12-03 17:05 UTC, Debas-31 commented on index.html
> +        </p>
- [ ] It would be better to wrap the heading in the header tag instead of the p tag. Kindly fix it :wrench: with header tag h1.

2022-12-03 17:05 UTC, Debas-31 commented on index.html
> +        </div>
- [ ] This should be your page's toolbar, and you should use proper HTML tags to wrap the elements for better semantics and increase the SEO of your page. Kindly wrap this section in a header tag. Typically the header tag is used as a page header. It contains the site's title or logo (or both) and the main site navigation. Check[ this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.

Example
```
<header role="banner">
    <nav>
       <a href=" "> logo </a>
      <img src=" " alt="Hamberger menu" />
    </nav>
</header>

```

2022-12-03 17:05 UTC, Debas-31 commented on README.md
> +🤝 Contributing
- [ ]  Well done adding a README to make a professional readme file; kindly customize the sections, and fill the sections as you can based on this milestone project. And the content is not well arranged as the [Microverse template](https://github.com/microverseinc/readme-template/blob/master/README.md), so [use markdown ](https://www.markdownguide.org/basic-syntax/) to arrange those issues.

2022-12-03 21:43 UTC, ridwanediallo requested changes
Hi @kingnoel , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linters errors. Please make sure to fix them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-04 17:59 UTC, kingnoel commented
> Hi @kingnoel ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has linters errors. Please make sure to fix them.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

the linters has been fixed.
Kindly check and let me know!

2022-12-05 10:57 UTC, OyePriscilla approved these changes
Hi @kingnoel   👍 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Linters check passed ✔️ 
GitHub flow observed 😄 

## Optional suggestions
[optional] Ensure that your subsequent feature branch is named according to your current milestone, this will make your project more professional. ℹ️ 
[optional] Kindly adjust your Readme file for readability. You may want to start editing [this template](https://github.com/microverseinc/readme-template/blob/master/README.md) starting from line 60. But ensure to remove unnecessary comments. 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 10:57 UTC, OyePriscilla commented on index.html
> +        </ul>
- [optional] Kindly ensure that the social media handles are aligned properly according to the template given. 👍  

## Figma design
![papaa](https://user-images.githubusercontent.com/103386183/205618891-c2b386b3-bdf9-46d0-9071-1683170c5dd6.png)

2022-12-05 14:07 UTC, merged